# 启动命令：java -jar sample.jar --server.port=80
server:
  port: ${CV_CLOUDPLATFORM_SERVER_PORT:8080}
  servlet:
    session:
      timeout: PT30M

spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging:
  level:
    org.springframework.security: INFO
    org.springframework.boot: INFO
    com.commvault.client.service.impl.CvCommonServiceImpl: DEBUG
    com.commvault.cloudplatform.controller: DEBUG


